-- Drop and Create Database
DROP DATABASE IF EXISTS BANK;
CREATE DATABASE BANK;
USE BANK;
COMMIT;

-- 1️⃣ ACCOUNT_DETAILS TABLE (Stores User Information)
CREATE TABLE ACCOUNT_DETAILS (
    USERID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    USERNAME VARCHAR(50) UNIQUE NOT NULL,
    PASSWORD VARCHAR(50) NOT NULL,
    ACCOUNT_NUMBER VARCHAR(20) UNIQUE NOT NULL,
    BALANCE DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    PHONE VARCHAR(15) NOT NULL
);

-- 2️⃣ LOGIN_DETAILS TABLE (Tracks User Login and Logout)
CREATE TABLE LOGIN_DETAILS (
    LOGIN_ID INT AUTO_INCREMENT PRIMARY KEY,
    USERID INT NOT NULL,
    USERNAME VARCHAR(50) NOT NULL,
    ACCOUNT_NUMBER VARCHAR(50) NOT NULL,
    STATUS ENUM('SUCCESS', 'FAILURE') NOT NULL,
    LOGIN_TIME DATETIME DEFAULT NOW(),
    LOGOUT_TIME DATETIME NULL,
    FOREIGN KEY (USERID) REFERENCES ACCOUNT_DETAILS(USERID) ON DELETE CASCADE
);

-- 3️⃣ TRANSACTION_DETAILS TABLE (Tracks All Transactions)
CREATE TABLE TRANSACTION_DETAILS (
    TRANSACTION_ID INT AUTO_INCREMENT PRIMARY KEY,
    USERID INT,  -- Sender ID (NULL for deposits)
    RECEIVER_ID INT,  -- Receiver ID (NULL for withdrawals)
    USER_ACC VARCHAR(50) NOT NULL,  
    RECEIVE_ACC VARCHAR(50),  
    TRANSACTION_TYPE ENUM('DEPOSIT', 'WITHDRAW', 'TRANSFER') NOT NULL,  
    AMOUNT DECIMAL(10,2) NOT NULL,  
    TRANSACTION_TIME DATETIME DEFAULT NOW(),
    FOREIGN KEY (USERID) REFERENCES ACCOUNT_DETAILS(USERID) ON DELETE CASCADE,
    FOREIGN KEY (RECEIVER_ID) REFERENCES ACCOUNT_DETAILS(USERID) ON DELETE CASCADE
);

-- 4️⃣ TRANSACTION_HISTORY TABLE (Maintains Detailed History)
CREATE TABLE TRANSACTION_HISTORY (
    HISTORY_ID INT AUTO_INCREMENT PRIMARY KEY,
    TRANSACTION_ID INT NOT NULL,
    USERID INT NOT NULL,
    ACCOUNT_NUMBER VARCHAR(50) NOT NULL,
    TRANSACTION_TYPE ENUM('DEPOSIT', 'WITHDRAW', 'TRANSFER') NOT NULL,
    AMOUNT DECIMAL(10,2) NOT NULL,
    BALANCE_AFTER_TRANSACTION DECIMAL(10,2) NOT NULL,
    TRANSACTION_TIME DATETIME DEFAULT NOW(),
    FOREIGN KEY (TRANSACTION_ID) REFERENCES TRANSACTION_DETAILS(TRANSACTION_ID) ON DELETE CASCADE,
    FOREIGN KEY (USERID) REFERENCES ACCOUNT_DETAILS(USERID) ON DELETE CASCADE
);

-- ✅ Insert Sample Data (Users)
INSERT INTO ACCOUNT_DETAILS (NAME, USERNAME, PASSWORD, ACCOUNT_NUMBER, BALANCE, PHONE) VALUES
('VINAY', 'VINAY_USER', 'VI12345AY', '1234567001', 10000.00, '9948112196'),
('ESHWAR', 'ESHWAR_USER', 'ES12345AR', '1234567002', 10000.00, '7834127845'),
('RAGHU', 'RAGHU_USER', 'RA12345HU', '1234567003', 10000.00, '8934772380');

-- ✅ Clearing Data if Needed
SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE TRANSACTION_HISTORY;
TRUNCATE TABLE TRANSACTION_DETAILS;
TRUNCATE TABLE LOGIN_DETAILS;
SET FOREIGN_KEY_CHECKS = 1;
COMMIT;

-- ✅ Display Tables (Testing)
SELECT * FROM ACCOUNT_DETAILS;
SELECT * FROM LOGIN_DETAILS;
SELECT * FROM TRANSACTION_DETAILS;
SELECT * FROM TRANSACTION_HISTORY;
commit;